# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: argocd-appset-checked-pr-generator
  namespace: argocd-appset-checked-pr-generator
spec:
  type: ClusterIP
  ports:
    - name: argocd-appset-checked-pr-generator
      port: 80
      targetPort: 3000
---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-appset-checked-pr-generator
spec:
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-sdk: "telemetry/default-instrumentation"
    spec:
      containers:
        - name: argocd-appset-checked-pr-generator
          image: lhr.ocir.io/lrdyqp2xtoja/argocd-appset-checked-pr-generator
          env:
            - name: RUST_LOG
              value: info,tower_http,argocd_appset_checked_pr_generator=debug
            - name: GITHUB_APP_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: argocd-appset-checked-pr-plugin-secret
                  key: GITHUB_APP_PRIVATE_KEY
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: argocd-appset-checked-pr-plugin-secret
                  key: GITHUB_APP_ID
            - name: ARGOCD_PLUGIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: argocd-appset-checked-pr-plugin-secret
                  key: ARGOCD_PLUGIN_TOKEN
          envFrom:
          resources:
            requests:
              cpu: 5m
              memory: 1Mi
            limits:
              cpu: 100m
              memory: 100Mi
      imagePullSecrets:
        - name: oracle-container-registry
---

